- adds init, stop, start commands - changes timeout to start only if a timeout is set - fixes a few runtime engine bugs - fixes workspace manager bug of not copying permission of file and folders - fixes wrapper script bugs

diff --git a/spidersilk/src/main/resources/wrapper_script b/spidersilk/src/main/resources/wrapper_script
--- a/spidersilk/src/main/resources/wrapper_script
+++ b/spidersilk/src/main/resources/wrapper_script
@@ -1,10 +1,22 @@
 #!/bin/sh
 
-# Start the first process
-{{RUN_COMMAND}} >> /spidersilk_out_err 2>&1
+env
+
+# run the init command
+if [ $(cat /spidersilk_do_init) = "1" ]; then
+    {{INIT_COMMAND}}
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo "Failed to start {{INIT_COMMAND}}: $status"
+      exit $status
+    fi
+fi
+
+# run the start command
+{{START_COMMAND}}
 status=$?
 if [ $status -ne 0 ]; then
-  echo "Failed to start {{RUN_COMMAND}}: $status"
+  echo "Failed to start {{START_COMMAND}}: $status"
   exit $status
 fi
 
